services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\EshopCommunity\Internal\Password\Bridge\PasswordServiceBridgeInterface:
    class: OxidEsales\EshopCommunity\Internal\Password\Bridge\PasswordServiceBridge
    public: true

  OxidEsales\EshopCommunity\Internal\Password\Service\PasswordHashServiceFactoryInterface:
    class: OxidEsales\EshopCommunity\Internal\Password\Service\PasswordHashServiceFactory

  OxidEsales\EshopCommunity\Internal\Password\Service\PasswordHashBcryptServiceOptionsProvider:
    class: OxidEsales\EshopCommunity\Internal\Password\Service\PasswordHashBcryptServiceOptionsProvider

  OxidEsales\EshopCommunity\Internal\Password\Service\PasswordHashBcryptService:
    class: OxidEsales\EshopCommunity\Internal\Password\Service\PasswordHashBcryptService
    public: true

  OxidEsales\EshopCommunity\Internal\Password\Service\PasswordHashArgon2iService:
    class: OxidEsales\EshopCommunity\Internal\Password\Service\PasswordHashArgon2iService
    public: true

  OxidEsales\EshopCommunity\Internal\Password\Service\PasswordHashArgon2idService:
    class: OxidEsales\EshopCommunity\Internal\Password\Service\PasswordHashArgon2idService
    public: true

  OxidEsales\EshopCommunity\Internal\Password\Service\PasswordVerificationServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Password\Service\PasswordVerificationService

  OxidEsales\EshopCommunity\Internal\Password\Service\PasswordPolicyServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Password\Service\PasswordPolicyService